name: kente_codeweaver
description: An AI-driven storytelling and block-based coding app for children.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^3.0.0
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_tts: ^4.2.2
  provider: ^6.1.1
  path_provider: ^2.1.2
  uuid: ^4.5.1
  audioplayers: ^6.0.0
  http: ^1.2.0  # Added for service HTTP requests
  get_it: ^8.0.3  # Added for dependency injection
  cached_network_image: ^3.3.1  # For caching network images
  flutter_cache_manager: ^3.3.1  # For managing cached assets
  flutter_svg: ^2.0.9  # For SVG support if needed
  package_info_plus: ^8.3.0  # For app version information
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
    - assets/audio/
    - assets/fonts/
    - assets/data/blocks.json
    - assets/data/challenges.json
    - assets/data/colors_cultural_info.json
    - assets/data/cultural_coding_mappings.json
    - assets/data/patterns_cultural_info.json
    - assets/data/regional_info.json
    - assets/data/stories.json
    - assets/data/symbols_cultural_info.json

  # Fonts configuration can be added here when custom fonts are needed
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700
